stages:
  - build
  - test

include:
  - template: Jobs/Build.gitlab-ci.yml
  - template: Jobs/Container-Scanning.gitlab.ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml


custom job:
  stage: test
  script:
    - python -m pytest

custom job:
  stage: test
  runs-on: ubuntu-latest
  script:
    - docker build . --file pipenv.Dockerfile --tag my-image-name:$(date +%s