DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS staff;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE staff (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  full_name TEXT NOT NULL,
  job_role TEXT NOT NULL,
  email TEXT NOT NULL,
  FOREIGN KEY (full_name) REFERENCES staff (id)
);